import json
import re
from llm_setup import llm


def generate_context_explanations(context, detection, features):

    prompt = f"""
You are a cybersecurity SOC analyst.

Explain the following contextual risk metrics.

IMPORTANT RULES:
- Do NOT repeat the metric values.
- Do NOT return numbers or labels.
- Provide explanations only.
- Each explanation must contain 2–3 sentences.

Return ONLY JSON in this format:

{{
"base_risk": "Explanation...",
"asset_modifier": "Explanation...",
"network_modifier": "Explanation...",
"security_modifier": "Explanation...",
"final_contextual_risk": "Explanation...",
"risk_band": "Explanation...",
"confidence_band": "Explanation..."
}}

Metrics:

Base Risk = {context.get("base_risk")}
Asset Modifier = {context.get("asset_modifier")}
Network Modifier = {context.get("network_modifier")}
Security Modifier = {context.get("security_modifier")}
Final Contextual Risk = {context.get("final_contextual_risk")}
Risk Band = {context.get("risk_band")}
Confidence Band = {context.get("confidence_band")}

Device Context:
{features}
"""

    try:

        # Correct LangChain invocation
        response = llm.invoke([
            {"role": "user", "content": prompt}
        ])

        content = response.content if hasattr(response, "content") else str(response)

        print("LLM RESPONSE:", content)

        # Extract JSON safely
        json_match = re.search(r"\{.*\}", content, re.DOTALL)

        if not json_match:
            raise ValueError("No JSON found in response")

        explanations = json.loads(json_match.group())

        # Prevent numeric echo or value repetition
        for key, value in explanations.items():
            if isinstance(value, (int, float)) or value == context.get(key):
                explanations[key] = "Explanation generation failed. Please retry."

        return explanations

    except Exception as e:

        print("LLM ERROR:", e)

        # Fallback explanations
        return {
            "base_risk": (
                "Base risk represents the combined anomaly probability and deviation score "
                "generated by the detection models. It reflects how abnormal the device "
                "behavior appears compared to baseline activity patterns. Higher values "
                "indicate stronger anomaly signals detected in the system."
            ),

            "asset_modifier": (
                "Asset modifier reflects the importance and criticality level of the device "
                "within the infrastructure. Devices belonging to sensitive departments or "
                "critical services increase contextual risk. Higher asset criticality "
                "amplifies the impact of suspicious behavior."
            ),

            "network_modifier": (
                "Network modifier evaluates abnormal network activity such as unusual ports, "
                "unexpected outbound traffic, or connections to external IP addresses. "
                "These signals may indicate command-and-control communication or data "
                "exfiltration attempts."
            ),

            "security_modifier": (
                "Security modifier captures alerts such as privilege escalation attempts, "
                "configuration changes, antivirus warnings, and failed authentication "
                "events. These indicators significantly increase the likelihood of "
                "malicious activity occurring on the device."
            ),

            "final_contextual_risk": (
                "Final contextual risk combines anomaly detection outputs with contextual "
                "modifiers such as asset importance, network activity, and security alerts. "
                "This value represents the overall threat severity assessed by the SOC "
                "analysis pipeline."
            ),

            "risk_band": (
                "Risk band categorizes the contextual risk score into operational severity "
                "levels such as LOW, MEDIUM, or HIGH. Higher bands indicate stronger "
                "evidence of suspicious activity and require faster SOC response."
            ),

            "confidence_band": (
                "Confidence band reflects the certainty of the anomaly detection models. "
                "Higher uncertainty reduces the confidence of automated decisions and may "
                "require human analyst verification."
            )
        }